### ISSUE TITLE
UI improvements for "This Week on FanFares" view

### ISSUE THREAD

**Issue by arkin0x** [fanfares/fanfares#46]
- [x] add the user's profile picture into the design somehow so you don't have to rely on the cover art to know who's podcast it is.
- [x] we should add the podcast name to the podcast card, perhaps under the short description and in slightly faded color.

**Comment by wemersonqueiroz** [comment]
![Screenshot 2024-06-07 122932](https://github.com/fanfares/fanfares/assets/25623830/c906946e-0f5c-4bff-b0fe-bf2b4954d935)

**Comment by wemersonqueiroz** [comment]
Done and merged

**Comment by arkin0x** [comment]
Nice work! Thank you!
