### ISSUE TITLE
Simplify onboarding with nostr-login

### ISSUE THREAD

**Issue by arkin0x** [fanfares/fanfares#47]
- [x] please research nostr-login https://github.com/nostrband/nostr-login
- [x] discuss nostr-login capabilities and user onboarding flow with team
- [x] implement improved user onboarding
- [x] test and approve new onboarding

**Comment by rleed** [comment]
Nostr-login has been added on branch `rl-nostr-login`.
Initial observations/issues to address:
- [ ] reloading some pages (e.g. player page) results in loss of plugin
- [ ] need our own nsec.app solution

**Comment by arkin0x** [comment]
> * [ ]  reloading some pages (e.g. player page) results in loss of plugin

Can you test if this happens on other clients when using an nsec.app login? I'm wondering if there is some trick we need to do with localstorage.

**Comment by arkin0x** [comment]
- [x] I'll take a look at `rl-nostr-login` branch to see if I can find out anything about it not initializing the login.

**Comment by arkin0x** [comment]
- [x] add `login.fanfares.io` to nostr login data-bunker option.

**Comment by arkin0x** [comment]
Need to watch for the nlAuth event so we can trigger `accountSetNostr` and `accountFetchProfile` (see line 50 of /apps/fanfares/src/app/components/AppController.tsx). We need to set up the account in the zustand store with these function calls after nostr-login gets us logged in. If you login and then refresh the homepage, this is fixed, but we don't want to rely on a refresh so we need to trigger it manually after login.

- [x] set up identity in store after nlAuth event @arkin0x

**Comment by arkin0x** [comment]
Closed with #62
