### ISSUE TITLE
Test fanfares/fanfares across devices

### ISSUE THREAD

**Issue by arkin0x** [fanfares/fanfares#73]
| # | Browser | OS | Action | Result | Pass/Fail | How to Fix | Assigned to | Fixed |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | Safari | iOS | Buy Podcast button | nostr-login modal activated when not logged in | ✅ | | | |
| 2 | Safari | iOS | Buy Podcast button > nostr-login Sign Up | cannot set a password | ❌ | see https://nsec.app/ios.html | tbd | ❌ |
| 3 | Safari | iOS | nsec.app > create account | account created | ✅ | | | |
| 4 | Safari | iOS | nostr-login Login > use previously created account | nostr-login opens tab; connection succeeds; login success | ✅ | | | |

**Comment by rleed** [comment]
2. fix is live

**Comment by arkin0x** [comment]
- nsecbunker sign in simply doesn't work on iOS 16.
- the latest iOS is 17.5.x unless you sign up for public beta for 17.6 or 18.x, so we shouldn't expect the general public to be on anything higher than 17.5.x

On iOS 17.5, you need to follow these steps to make nsec.app work:
1. install use.nsec.app as a PWA
2. add your account on the PWA
3. login with nostr-login and specify the account on the PWA
4. click "Continue" when the login screen says "Almost Ready!"
5. use.nsec.app will open in a new tab (instead of PWA). Click Connect
6. now you're logged in

On iOS 18, clicking "Continue" will actually switch to the PWA

We were not able to get account creation to work on any version of iOS because it tries to use push notifications in the browser. So it is pretty much a prerequisite that the iOS user has an account already on use.nsec.app PWA before they try to login.
